### ISSUE TITLE
Running DML analysis 

### ISSUE THREAD

**Issue by RVB-1104** [Stefanos-Apostle/SeSAMeStr#4]
Hi.
Methylation analysis is being performed on mm285.
However, when analyzing DML, I encountered the following error code

Error in smry[[1]]: subscript out of bounds.

**Comment by Stefanos-Apostle** [comment]
Is your sample_name column in the sample sheet matching the idat file names format? If your idats have the following naming scheme; 

> XXXXXX_R06C02_Grn.idat

your sample_name column should be the following to match the Grn and Red file names;

> XXXXXX_R06C02

**Comment by RVB-1104** [comment]
Thank you for your kind reply.
My sample sheet name is below
<img width="871" alt="image" src="https://user-images.githubusercontent.com/123035805/213344467-00e56a84-a090-4f4a-b51f-65837cec9354.png">

My sample_name is below 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/123035805/213343985-1bf714e3-b54a-4eae-8296-68bbc66da63c.png">
Both are the same, so what's the problem?
Thank you

**Comment by Stefanos-Apostle** [comment]
Just changed this, the original idea was that sample_name was the idat file name prefix (ie '205333490035_R04C02'), but this has proved to be counterintuitive a couple times now so IDAT is now the required column for these prefixes. I edited the necessary lines and this should now work for you, since this was causing you to generate an empty data table as input to DML, resulting in a smry object of length 0. Please reinstall with 'force=T'

**Comment by RVB-1104** [comment]
I reinstalled but still got the same error code.

Error code 
: 

Loading in sample sheet
New names:                                                                                                  
• `` -> `...1`
• `` -> `...2`
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
Loading in betas.RData
Calculating summary statistics
Loading in smry.RData
Running DML analysis
Error in smry[[1]]: subscript out of bounds.
